version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-trc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wmvfd4nayj04"
s3_prefix = "test-trc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ENVIRONMENT=\"ABU\""
image_repositories = []
