AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  TRC Serverless Template

Globals:
  Function:
    Timeout: 15

Parameters:
  ENVIRONMENT:
    Description: "Required. Enviroment that will be deployed in"
    Type: "String"

Resources:
  EventAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "EventAPI"
      StageName: Prod

  EventsGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "EventsGet"
      CodeUri: lambdas/events/get
      Handler: getEvents.getEvents
      Runtime: python3.8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Sub "Events"
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${ENVIRONMENT}"
      Events:
        GetEvents:
          Type: Api
          Properties:
            RestApiId: !Ref EventAPI
            Path: /api/events
            Method: GET

  Live_EventsDynamoDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "Events_Live"
      AttributeDefinitions:
        - AttributeName: EventID
          AttributeType: S
      KeySchema:
        - AttributeName: EventID
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST

  Live_TransactionDynamoDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "User_Transactions_Live"
      AttributeDefinitions:
        - AttributeName: EventID
          AttributeType: S
      KeySchema:
        - AttributeName: EventID
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST

  Dev_EventsDynamoDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "Events_Dev"
      AttributeDefinitions:
        - AttributeName: EventID
          AttributeType: S
      KeySchema:
        - AttributeName: EventID
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST

  Dev_TransactionDynamoDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "User_Transactions_Dev"
      AttributeDefinitions:
        - AttributeName: EventID
          AttributeType: S
      KeySchema:
        - AttributeName: EventID
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST

  #EventsGet:
  #Type: AWS::Serverless::Function

  #TransactionPost:
  #Type: AWS::Serverless::Function

  #EventDatabase
  #Type: AWS::Dynamo::Table

  #TransactionDatabase:
  #Type: AWS::Dynamo::Table
